### ISSUE TITLE
Display actual line numbers in View Source Code

### ISSUE THREAD

**Issue by TrudAX** [arbelatech/aotbrowser#14]
Hi
Thanks for such a great tool. Just an idea to improve - if you view a method source line numbering for every method starts with 1..
Is it possible to display the actual line number for the method in View Source Code. In should be the same as in Visual studio
![image](https://user-images.githubusercontent.com/26786918/134116766-b485e7cd-af0b-47b4-b8fd-cc40223a56c8.png)

**Comment by caleblanchard** [comment]
Thank you for the suggestion. We will take a look and see if that is something we can do.

**Comment by caleblanchard** [comment]
We have added the ability to view the complete source for an object. This feature should enable you to view the actual line numbers so that they would match up with what Visual Studio has. This is included in 863.0.4.1.
