### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by MTCostello** [arbelatech/aotbrowser#15]
1. Do you have plans to allow users to Browse a data entity similar to a table?
2. Isn't viewing a data entity the same viewing the data from a View?

**Comment by caleblanchard** [comment]
The AOT browser does not provide the functionality for browsing tables/views. It only calls the built in table browser from MS to view the data. The built in table browser does not support viewing the data from the data entities.

**Comment by JFLandryBiron** [comment]
Hello,
I just downloaded the latest version of the application and double click on _AXMergeDeployablePackage.exe_ for the installation of the _ATO Browser_ in Microsoft D365 FO. The program does not start a standard installer but appears to open and close a prompt window. I don't see the extension in Common - Common in my version of D365 FO. Is there a standard procedure for installation? Do I have to have special rights?
Thanks

**Comment by caleblanchard** [comment]
Here is a link from Microsoft on how to install deployable packages in D365FO: https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/install-deployable-package
