### ISSUE TITLE
Error when build Project

### ISSUE THREAD

**Issue by dianp83** [arbelatech/aotbrowser#21]
Hi AOTBrowser team,

Firstly., thank you for creating this model and actively update it.

We want to create package deployment consist of our models and AOTBrowser model. There is no issue when creating package manually from DEV machine or from Build VM. But now we are migrating the build to Azure build.
One of the requirement during compilation is to create a VS solution containing projects for each model. This VS solution will run by Azure pipeline to build and create package. For more information, you can refer to this: https://ariste.info/en/dynamics365almguide/configure-pipeline/

Although the package is created and successfully deployed, AOTBrowser form is unable to open and error: "Common Language Runtime detected an invalid program". The other error that is often appear is "unable to locate method AOTBrowser.update(boolean)".
Then I tried to build the project manually in VS, and same error appear when click AOTBrowser tile. But when I build the model, the error disappear, although a warning message appear: An error occurred while loading assembly 'Dynamics.AX.AOTBrowser, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null': 'Object reference not set to an instance of an object.'

So, the question are:
1. How to build the project without resulting error?
2. How to solve the warning message when loading assembly?

Thank you in advance.

**Comment by caleblanchard** [comment]
How did you get the AOTBrowser code into your repository? Did you download the code directly from the github repo and copy it in to your repo? Or did you go to the github release page and download the model file from there there and use the modelutil to import the model?

**Comment by dianp83** [comment]
Hi Caleb,

Thanks for your reply.

I went to Release, download the Source code and copy it.

Based on your statement, I should import the model using modelutil?

**Comment by caleblanchard** [comment]
Yes. I would use either the model or the deployable package. In order to use the source code directly, it would be more complicated because it includes a c# project that would also need to get built.

**Comment by dianp83** [comment]
Hi Caleb,

I already import using modelutil, build the model. No error on DEV, but when deploy to UAT, have error: 
Method not found: 'Void Dynamics.AX.Application.ARBAOTBrowserConstants.updateProvider(Boolean)'.

Same error as before. I believe this is because the compilation through VS project,
Any idea what is the cause? Is it reference? But I already included Arbela.Dynamics.AX.Xpp.Support and PygmentSharp in the project.

**Comment by caleblanchard** [comment]
To be honest, I am not really sure what is happening here. It seems like something is not getting added to version control properly. Maybe try using the deployable package instead of the model and see if that works for you.

**Comment by dianp83** [comment]
Hi Caleb,

Issue is resolved. This video shows the correct way to create Azure build pipeline and the guy also mentioned about missing ISV component. https://www.youtube.com/watch?v=ffJHRtJHLKE&t=129s

Thanks for your reply.
