### ISSUE TITLE
Uncorrect string size on table fields

### ISSUE THREAD

**Issue by gotahistop** [arbelatech/aotbrowser#23]
Hi everyone, 
We've noticed lately that some table string fields have incorrect string size (always set to 10 when incorrect it seems).

For example, **CustTable field CustAccount** has **string size set to 20** and it appears as **10**.
We've implemented AOTBrowser in two customers so far and we've noticed the same behaviour on both.
Please find a screenshot below of the specified behaviour.
<img width="1277" alt="AOTB" src="https://user-images.githubusercontent.com/54377272/223422280-1d7f11e7-8583-4504-b716-7e755c671a3f.png">

Could you please elucidate on why this is happening?

In the meantime, I believe one of our developers is making efforts to fix this issue, is there a way to contribute to the project?

Thank you so much for your time.

**Comment by HieiOne** [comment]
I also found this issue and prepared a pull request #26
